language: python
python:
  - "3.5"
install:
  - "pip install -r test-requirements.txt"
script:
  - "flake8 ."
  - "py.test ."
after_script:
  - "coveralls"
  - "codecov"
notifications:
  email: false
