language: python
python:
  - "3.5"
install:
  - "pip install -r test-requirements.txt"
script:
  - "py.test --cov=itertools_ext --cov=math_ext --cov=problems --durations=100"
after_script:
  - "coveralls"
notifications:
  email: false
